---
islandora_spreadsheet_ingest.settings:
  type: config_object
  mapping:
    binary_directory_whitelist:
      type: sequence
      label: 'List of allowed source directories.'
      sequence:
        type: string

#islandora_spreadsheet_ingest.request_structure:
#  type: config_entity
#  mapping:
#    id:
#      type: string
#      label: ID
#    label:
#      type: label
#      label: Label
#    source:
#      type: mapping
#      mapping:
#        file:
#          type: entity:file
#          label: The spreadsheet file to process.
#        sheet:
#          type: string
#          label: The worksheet of the file to process.
#    mappings:
#      type: sequence
#      sequence:
#        migration:
#          type: mapping
#          mapping:
#            id:
#              type: string
#              label: ID
#            mappings:
#              type: sequence
#              sequence:
#                pipeline:
#                  type: sequence
#                  sequence:
#                    step:
#                      type: ignore
