---
islandora_spreadsheet_ingest.settings:
  type: config_object
  mapping:
    binary_directory_whitelist:
      type: sequence
      label: 'List of allowed source directories.'
      sequence:
        type: string

#islandora_spreadsheet_ingest.request_structure:
#  type: config_entity
#  mapping:
#    csv:
#      type: entity:file
#      label: The CSV file to process.
#    
